Availability date tool tip behaviour not consistent on iOS
BrightspaceHypermediaComponents/sequences pull request #300
Opened 2020-12-17 16:50 UTC by ianlaidlaw

There were a few problems with the tooltip in LX that this pr will fix:

1. On mobile, tapping on the avail dates to make the tooltip show was difficult as the tap area was very small.
2. Even if you tapped directly in the middle, the tap would go behind the date and perform the action of the element behind it. This could be expanding/collapsing, or even navigating into LX.
3. Tabbing to the avail dates (not mobile) was broken.

2020-12-17 16:51 UTC, ianlaidlaw commented on d2l-sequence-navigator/d2l-activity-link.js
> -				line-height: var(--d2l-body-small-text_-_line-height);
deleting this makes the height a little bigger, making tapping on the dates easier

2020-12-17 16:53 UTC, ianlaidlaw commented on d2l-sequence-navigator/d2l-activity-link.js
> +			_showDates: {
I think when making the tooltip, this function was missed in some files. It was attempting to call this for tabIndex, but this property/function did not exist

2020-12-17 16:53 UTC, ianlaidlaw commented on d2l-sequence-navigator/d2l-activity-link.js
> +	_getShowDates(properties) {
I got this from sequence launcher fra: https://github.com/Brightspace/sequence-launcher-fra/blob/master/components/d2l-sequence-launcher-accordion.js#L344

2020-12-17 16:53 UTC, ianlaidlaw commented on d2l-sequence-navigator/d2l-activity-link.js
> +	_getShowDates(properties) {
One difference is I shouldn't check for due dates. If there was a due date but not avail dates, this would have returned true and shown an empty tooltip when there wasn't actually an avail date

2020-12-17 16:54 UTC, ianlaidlaw commented on d2l-sequence-navigator/d2l-outer-module.js
> +	// Prevent navigating/collapsing the background element when
unfortunately there's lots of duplicated code with all the different files 😞

2020-12-17 16:59 UTC, ianlaidlaw commented on d2l-sequence-navigator/d2l-activity-link.js
> +		e.stopPropagation();
this is what prevents the click event from propagating up and causing the click to be registered by the element behind the availability dates text

2020-12-17 17:59 UTC, ChrisKraljevicD2L requested changes

2020-12-17 17:59 UTC, ChrisKraljevicD2L commented on d2l-sequence-navigator/d2l-lesson-header.js
> +		return startDate || endDate;
Switching this to only check availability dates will break CSS for lesson-header, since [`_getDateContainerClasses`](https://github.com/BrightspaceHypermediaComponents/sequences/blob/ilaidlaw/ios-tooltip/d2l-sequence-navigator/d2l-lesson-header.js#L246) takes in `_showDates`. If there is only a due date but no availability dates, the wrong classes will be applied.

I suggest altering `_getTabIndex` to take in `entity.properties` so it can work on only avail dates while `_showDates` can still use `dueDate`.

2020-12-17 18:03 UTC, ChrisKraljevicD2L commented on d2l-sequence-navigator/d2l-lesson-header.js
> +		return startDate || endDate;
Actually, your solution in [`sequence-launcher-fra`](https://github.com/Brightspace/sequence-launcher-fra/pull/178/files#r545283737) would work here too :+1:

2020-12-17 18:04 UTC, brissons commented on d2l-sequence-navigator/d2l-activity-link.js
> -				line-height: var(--d2l-body-small-text_-_line-height);
It looks like this was [added with availability dates](https://github.com/BrightspaceHypermediaComponents/sequences/pull/276). Double checking that removing this won't cause any ui formatting issues?

2020-12-17 18:05 UTC, ianlaidlaw commented on d2l-sequence-navigator/d2l-lesson-header.js
> +		return startDate || endDate;
good catch, ill adjust accordingly

2020-12-18 15:52 UTC, ianlaidlaw commented on d2l-sequence-navigator/d2l-activity-link.js
> -				line-height: var(--d2l-body-small-text_-_line-height);
yeah, it does slightly increase the height of the text area a little bit. i think i'm going to revert this because i don't think sarah realized that tap events were going through the text, I think maybe she thought the text area was really small and it was difficult to press it without accidentally pressing above or below it. so since i blocked those touch events from going behind, this isn't really doing much

2020-12-18 16:03 UTC, ianlaidlaw commented on d2l-sequence-navigator/d2l-activity-link.js
> -				line-height: var(--d2l-body-small-text_-_line-height);
increasing the height was a suggestion from Sarah + Tara. but I don't think we'll need to mess with the designs to fix this

2020-12-18 16:54 UTC, ChrisKraljevicD2L approved these changes

2020-12-18 17:14 UTC, merged