Update telemetry to record absolute URL
BrightspaceHypermediaComponents/sequences pull request #332
Opened 2021-09-07 18:02 UTC by Kiefer-Co-D2L

## Relevant Rally Links

- https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=/userstory/608174014131

## Description

> in the 20.21.10 release Telemetry events will have the URL enforced. In LX we pass the ID in the URL field. That needs to change to an absolute URL in order to conform to the event requirements.
> 
> 
> Here is the file that likely needs to be upgrades:
> 
> https://search.d2l.dev/xref/BrightspaceHypermediaComponents/sequences/helpers/telemetry-helper.js?r=85091531&fi=logTelemetryEvent#logTelemetryEvent
> 
> 
> When the below method is called, the first parameter should be an absolute URL the user is currently viewing.
> 
> `.setObject(encodeURIComponent(id), 'Sequence Viewer', id);`
>
> This improvement should be done for both Telemetry and Performance events.

## Goal/Solution

In `eventBody.js`, the signature for `setObject` is:

```javascript
setObject(id, type, url, value) {
```

In the telemetry and performance logging events, the URL parameter is changed to output `window.location.href`, which is the currently viewed URL (see screenshot).
The id parameter will be passed the id and the type is unchanged.

## Video/Screenshots

Temporary alert showing what would be recorded in the URL field of the event:

![Telemetry Test](https://user-images.githubusercontent.com/89945180/132389226-190746ed-2218-4e91-828c-3714f32b5c93.PNG)

## Related PRs

- N/A

## Remaining Work

- [ ] Dev Testing: another developer will test this code on their machine

2021-09-08 14:06 UTC, pbrown-d2l requested changes

2021-09-08 14:06 UTC, pbrown-d2l commented on helpers/telemetry-helper.js
> +			.setObject(id, 'Sequence Viewer', window.location.href);
based on the comment [here](https://search.d2l.dev/xref/Brightspace/d2l-telemetry-browser-client/) it looks like the id might still need to be encoded to avoid certain characters due to a limitation in the BDP processing

2021-09-09 16:13 UTC, coffeexcode approved these changes

2021-09-09 20:46 UTC, ianlaidlaw approved these changes

2021-09-10 14:01 UTC, brissons approved these changes

2021-09-16 14:13 UTC, pbrown-d2l approved these changes

2021-09-16 14:13 UTC, merged